export const newMaps = [
    {name: "Paris Promenade", image: require('@/assets/images/New Maps/Golden Dash Cup/Paris Promenade.png')},
    {name: "Toad Circuit", image: require('@/assets/images/New Maps/Golden Dash Cup/Toad Circuit.png')},
    {name: "Choco Mountain", image: require('@/assets/images/New Maps/Golden Dash Cup/Choco Mountain.png')},
    {name: "Coconut Mall", image: require('@/assets/images/New Maps/Golden Dash Cup/Coconut Mall.png')},
    {name: "Tokyo Blur", image: require('@/assets/images/New Maps/Lucky Cat Cup/Tokyo Blur.png')},
    {name: "Shroom Ridge", image: require('@/assets/images/New Maps/Lucky Cat Cup/Shroom Ridge.png')},
    {name: "Sky Garden", image: require('@/assets/images/New Maps/Lucky Cat Cup/Sky Garden.png')},
    {name: "Ninja Hideaway", image: require('@/assets/images/New Maps/Lucky Cat Cup/Ninja Hideaway.png')},
    {name: "New York Minute", image: require('@/assets/images/New Maps/Turnip Cup/New York Minute.png')},
    {name: "Mario Circuit 3", image: require('@/assets/images/New Maps/Turnip Cup/Mario Circuit 3.png')},
    {name: "Kalimari Desert", image: require('@/assets/images/New Maps/Turnip Cup/Kalimari Desert.png')},
    {name: "Waluigi Pinball", image: require('@/assets/images/New Maps/Turnip Cup/Waluigi Pinball.png')},
    {name: "Sydney Sprint", image: require('@/assets/images/New Maps/Propeller Cup/Sydney Sprint.png')},
    {name: "Snow Land", image: require('@/assets/images/New Maps/Propeller Cup/Snow Land.png')},
    {name: "Mushroom Gorge", image: require('@/assets/images/New Maps/Propeller Cup/Mushroom Gorge.png')},
    {name: "Sky-High Sundae", image: require('@/assets/images/New Maps/Propeller Cup/Sky-High Sundae.png')},
    {name: "London Loop", image: require('@/assets/images/New Maps/Rock Cup/London Loop.png')},
    {name: "Boo Lake", image: require('@/assets/images/New Maps/Rock Cup/Boo Lake.png')},
    {name: "Rock Rock Mountain", image: require('@/assets/images/New Maps/Rock Cup/Rock Rock Mountain.png')},
    {name: "Maple Treeway", image: require('@/assets/images/New Maps/Rock Cup/Maple Treeway.png')},
]
