export const newMaps = [
    {name: "Paris Promenade", image: require('@/assets/images/New Maps/Golden Dash Cup/Paris Promenade.png')},
    {name: "Toad Circuit", image: require('@/assets/images/New Maps/Golden Dash Cup/Toad Circuit.png')},
    {name: "Choco Mountain", image: require('@/assets/images/New Maps/Golden Dash Cup/Choco Mountain.png')},
    {name: "Coconut Mall", image: require('@/assets/images/New Maps/Golden Dash Cup/Coconut Mall.png')},
    {name: "Tokyo Blur", image: require('@/assets/images/New Maps/Lucky Cat Cup/Tokyo Blur.png')},
    {name: "Shroom Ridge", image: require('@/assets/images/New Maps/Lucky Cat Cup/Shroom Ridge.png')},
    {name: "Sky Garden", image: require('@/assets/images/New Maps/Lucky Cat Cup/Sky Garden.png')},
    {name: "Ninja Hideaway", image: require('@/assets/images/New Maps/Lucky Cat Cup/Ninja Hideaway.png')},
    {name: "New York Minute", image: require('@/assets/images/New Maps/Turnip Cup/New York Minute.png')},
    {name: "Mario Circuit 3", image: require('@/assets/images/New Maps/Turnip Cup/Mario Circuit 3.png')},
    {name: "Kalimari Desert", image: require('@/assets/images/New Maps/Turnip Cup/Kalimari Desert.png')},
    {name: "Waluigi Pinball", image: require('@/assets/images/New Maps/Turnip Cup/Waluigi Pinball.png')},
    {name: "Sydney Sprint", image: require('@/assets/images/New Maps/Propeller Cup/Sydney Sprint.png')},
    {name: "Snow Land", image: require('@/assets/images/New Maps/Propeller Cup/Snow Land.png')},
    {name: "Mushroom Gorge", image: require('@/assets/images/New Maps/Propeller Cup/Mushroom Gorge.png')},
    {name: "Sky-High Sundae", image: require('@/assets/images/New Maps/Propeller Cup/Sky-High Sundae.png')},
    {name: "London Loop", image: require('@/assets/images/New Maps/Rock Cup/London Loop.png')},
    {name: "Boo Lake", image: require('@/assets/images/New Maps/Rock Cup/Boo Lake.png')},
    {name: "Rock Rock Mountain", image: require('@/assets/images/New Maps/Rock Cup/Rock Rock Mountain.png')},
    {name: "Maple Treeway", image: require('@/assets/images/New Maps/Rock Cup/Maple Treeway.png')},
    {name: "Berlin Byways", image: require('@/assets/images/New Maps/Moon Cup/Berlin Byways.png')},
    {name: "Peach Gardens", image: require('@/assets/images/New Maps/Moon Cup/Peach Gardens.png')},
    {name: "Merry Mountain", image: require('@/assets/images/New Maps/Moon Cup/Merry Mountain.png')},
    {name: "Rainbow Road 3DS", image: require('@/assets/images/New Maps/Moon Cup/Rainbow Road.png')},
    {name: "Amsterdam Drift", image: require('@/assets/images/New Maps/Fruit Cup/Amsterdam Drift.png')},
    {name: "Riverside Park", image: require('@/assets/images/New Maps/Fruit Cup/Riverside Park.png')},
    {name: "DK Summit", image: require('@/assets/images/New Maps/Fruit Cup/DK Summit.png')},
    {name: "Yoshi's Island", image: require('@/assets/images/New Maps/Fruit Cup/Yoshi Island.png')},
    {name: "Bangkok Rush", image: require('@/assets/images/New Maps/Boomerang Cup/Bangkok Rush.png')},
    {name: "Mario Circuit DS", image: require('@/assets/images/New Maps/Boomerang Cup/Mario Circuit.png')},
    {name: "Waluigi Stadium", image: require('@/assets/images/New Maps/Boomerang Cup/Waluigi Stadium.png')},
    {name: "Singapore Speedway", image: require('@/assets/images/New Maps/Boomerang Cup/Singapore Speedway.png')},
    {name: "Athens Dash", image: require('@/assets/images/New Maps/Feather Cup/Athens Dash.png')},
    {name: "Daisy Cruiser", image: require('@/assets/images/New Maps/Feather Cup/Daisy Cruiser.png')},
    {name: "Moonview Highway", image: require('@/assets/images/New Maps/Feather Cup/Moonview Highway.png')},
    {name: "Squeaky Clean Sprint", image: require('@/assets/images/New Maps/Feather Cup/Squeaky Clean Sprint.png')},
    {name: "Los Angeles Laps", image: require('@/assets/images/New Maps/Cherry Cup/Los Angeles Laps.png')},
    {name: "Sunset Wilds", image: require('@/assets/images/New Maps/Cherry Cup/Sunset Wilds.png')},
    {name: "Koopa Cape", image: require('@/assets/images/New Maps/Cherry Cup/Koopa Cape.png')},
    {name: "Vancouver Velocity", image: require('@/assets/images/New Maps/Cherry Cup/Vancouver Velocity.png')},
    {name: "Rome Avanti", image: require('@/assets/images/New Maps/Acorn Cup/Rome Avanti.png')},
    {name: "DK Mountain", image: require('@/assets/images/New Maps/Acorn Cup/DK Mountain.png')},
    {name: "Daisy Circuit", image: require('@/assets/images/New Maps/Acorn Cup/Daisy Circuit.png')},
    {name: "Piranha Plant Cove", image: require('@/assets/images/New Maps/Acorn Cup/Piranha Plant Cove.png')},
    {name: "Madrid Drive", image: require('@/assets/images/New Maps/Spiny Cup/Madrid Drive.png')},
    {name: "Rosalina's Ice World", image: require('@/assets/images/New Maps/Spiny Cup/Rosalinas Ice World.png')},
    {name: "Bowser Castle 3", image: require('@/assets/images/New Maps/Spiny Cup/Bowser Castle 3.png')},
    {name: "Rainbow Road Wii", image: require('@/assets/images/New Maps/Spiny Cup/Rainbow Road.png')},
    
]
