export const oldMaps = [
    {name: "Mario Kart Stadium", image: require('@/assets/images/Old Maps/Mushroom Cup/Mario Kart Stadium.png')},
    {name: "Water Park", image: require('@/assets/images/Old Maps/Mushroom Cup/Water Park.png')},
    {name: "Sweet Sweet Canyon", image: require('@/assets/images/Old Maps/Mushroom Cup/Sweet Sweet Canyon.png')},
    {name: "Thwomp Ruins", image: require('@/assets/images/Old Maps/Mushroom Cup/Thwomp Ruins.png')},
    {name: "Mario Circuit", image: require('@/assets/images/Old Maps/Flower Cup/Mario Circuit.png')},
    {name: "Toad Harbor", image: require('@/assets/images/Old Maps/Flower Cup/Toad Harbour.png')},
    {name: "Twisted Mansion", image: require('@/assets/images/Old Maps/Flower Cup/Twisted Mansion.png')},
    {name: "Shy Guy Falls", image: require('@/assets/images/Old Maps/Flower Cup/Shy Guy Falls.png')},
    {name: "Sunshine Airport", image: require('@/assets/images/Old Maps/Star Cup/Sunshine Airport.png')},
    {name: "Dolphin Shoals", image: require('@/assets/images/Old Maps/Star Cup/Dolphin Shoals.png')},
    {name: "Electrodrome", image: require('@/assets/images/Old Maps/Star Cup/Electrodome.png')},
    {name: "Mount Wario", image: require('@/assets/images/Old Maps/Star Cup/Mount Wario.png')},
    {name: "Cloudtop Cruise", image: require('@/assets/images/Old Maps/Special Cup/Cloudtop Cruise.png')},
    {name: "Bone Dry Dunes", image: require('@/assets/images/Old Maps/Special Cup/Bone-Dry Dunes.png')},
    {name: "Bowser's Castle", image: require('@/assets/images/Old Maps/Special Cup/Bowsers Castle.png')},
    {name: "Rainbow Road", image: require('@/assets/images/Old Maps/Special Cup/Rainbow Road.png')},
    {name: "Moo Moo Meadows", image: require('@/assets/images/Old Maps/Shell Cup/Moo Moo Meadows.png')},
    {name: "Mario Circuit GBA", image: require('@/assets/images/Old Maps/Shell Cup/Mario Circuit.png')},
    {name: "Cheep Cheep Beach", image: require('@/assets/images/Old Maps/Shell Cup/Cheep Cheep Beach.png')},
    {name: "Toad's Turnpike", image: require('@/assets/images/Old Maps/Shell Cup/Toads Turnpike.png')},
    {name: "Dry Dry Desert", image: require('@/assets/images/Old Maps/Banana Cup/Dry Dry Desert.png')},
    {name: "Donut Plains 3", image: require('@/assets/images/Old Maps/Banana Cup/Donut Plains 3.png')},
    {name: "Royal Raceway", image: require('@/assets/images/Old Maps/Banana Cup/Royal Raceway.png')},
    {name: "DK Jungle", image: require('@/assets/images/Old Maps/Banana Cup/DK Jungle.png')},
    {name: "Wario Stadium", image: require('@/assets/images/Old Maps/Leaf Cup/Wario Stadium.png')},
    {name: "Sherbet Land", image: require('@/assets/images/Old Maps/Leaf Cup/Sherbet Land.png')},
    {name: "Music Park", image: require('@/assets/images/Old Maps/Leaf Cup/Music Park.png')},
    {name: "Yoshi Valley", image: require('@/assets/images/Old Maps/Leaf Cup/Yoshi Valley.png')},
    {name: "Tick Tock Clock", image: require('@/assets/images/Old Maps/Lightning Cup/Tick-Tock Clock.png')},
    {name: "Piranha Plant Slide", image: require('@/assets/images/Old Maps/Lightning Cup/Piranha Plant Slide.png')},
    {name: "Grumble Volcano", image: require('@/assets/images/Old Maps/Lightning Cup/Grumble Volcano.png')},
    {name: "Rainbow Road N64", image: require('@/assets/images/Old Maps/Lightning Cup/Rainbow Road.png')},
    {name: "Yoshi Circuit", image: require('@/assets/images/Old Maps/Egg Cup/Yoshi Circuit.png')},
    {name: "Excitebike Arena", image: require('@/assets/images/Old Maps/Egg Cup/Excitebike Arena.png')},
    {name: "Dragon Driftway", image: require('@/assets/images/Old Maps/Egg Cup/Dragon Driftway.png')},
    {name: "Mute City", image: require('@/assets/images/Old Maps/Egg Cup/Mute City.png')},
    {name: "Wario's Gold Mine", image: require('@/assets/images/Old Maps/Triforce Cup/Warios Gold Mine.png')},
    {name: "Rainbow Road SNES", image: require('@/assets/images/Old Maps/Triforce Cup/Rainbow Road.png')},
    {name: "Ice Ice Outpost", image: require('@/assets/images/Old Maps/Triforce Cup/Ice Ice Outpost.png')},
    {name: "Hyrule Circuit", image: require('@/assets/images/Old Maps/Triforce Cup/Hyrule Circuit.png')},
    {name: "Baby Park", image: require('@/assets/images/Old Maps/Crossing Cup/Baby Park.png')},
    {name: "Cheese Land", image: require('@/assets/images/Old Maps/Crossing Cup/Cheese Land.png')},
    {name: "Wild Woods", image: require('@/assets/images/Old Maps/Crossing Cup/Wild Woods.png')},
    {name: "Animal Crossing", image: require('@/assets/images/Old Maps/Crossing Cup/Animal Crossing.png')},
    {name: "Neo Bowser City", image: require('@/assets/images/Old Maps/Bell Cup/Neo Bowser City.png')},
    {name: "Ribbon Road", image: require('@/assets/images/Old Maps/Bell Cup/Ribbon Road.png')},
    {name: "Super Bell Subway", image: require('@/assets/images/Old Maps/Bell Cup/Super Bell Subway.png')},
    {name: "Big Blue", image: require('@/assets/images/Old Maps/Bell Cup/Big Blue.png')},
]
